package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
)

type AutoGenerated struct {
	Books []struct {
		Title  string `json:"title"`
		Author string `json:"author"`
		Year   int    `json:"year"`
		Genre  string `json:"genre"`
	} `json:"books"`
}

func main() {
	var a AutoGenerated
	f, err := os.Open("package.json")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	reader := bufio.NewReader(f)
	file, err := ioutil.ReadAll(reader)
	if err != nil {
		panic(err)
	}
	// Unmarshaling given json
	err = json.Unmarshal(file, &a)
	if err != nil {
		panic(err)
	}

	// From JSON to struct
	fmt.Println(a.Books[0].Author)
}
